
version: "2"
services:
 web:
  build: .
  expose:
    - "8080"
  depends_on:
    - mongo
 mongo:
  image: mongo
  ports:
    - "27017:27017"
 nginx:
  image: nginx:latest
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
  depends_on:
    - web
  ports:
    - "4000:4000"
networks:
  default:
    driver: bridge
    name: cluster_network